### ISSUE TITLE
Translations (pt-br)

### ISSUE THREAD

**Issue by iraamaro** [steemit/whitepaper#28]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by plink01001** [comment]
Hi @hanelore . Any user is welcome to fork the repository and create a translation there. Currently we are not maintaining translated files in our official repository, but you are welcome to submit a pull request to add a link to your "unofficial translation" to the readme.

**Comment by iraamaro** [comment]
Thanks @plink01001
